apiVersion: v1
kind: Namespace
metadata:
  name: pen

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending
  namespace: pen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pending
  template:
    metadata:
      labels:
        app: pending
    spec:
      containers:
      - name: huge
        image: nginx
        resources:
          requests:
            memory: "1000Gi"
---

apiVersion: v1
kind: Namespace
metadata:
  name: oom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oomkilled
  namespace: oom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oomkilled
  template:
    metadata:
      labels:
        app: oomkilled
    spec:
      containers:
      - name: kubernetes
        image: polinux/stress
        args:
          - "--vm"
          - "1"
          - "--vm-bytes"
          - "256M"
          - "--vm-hang"
          - "1"

        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "128Mi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: image

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepullbackoff
  namespace: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagepullbackoff
  template:
    metadata:
      labels:
        app: imagepullbackoff
    spec:
      containers:
      - name: broken
        image: this-image-does-not-exist:latest

--- 

apiVersion: v1 
kind: Namespace
metadata:
  name: config

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configerror
  namespace: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configerror
  template:
    metadata:
      labels:
        app: configerror
    spec:
      containers:
      - name: app
        image: nginx
        env:
        - name: APP_CONFIG
          valueFrom:
            configMapKeyRef:
              name: missing-config
              key: value

---
apiVersion: v1 
kind: Namespace
metadata:
  name: container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: containererror
  namespace: container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containererror
  template:
    metadata:
      labels:
        app: containererror
    spec:
      containers:
      - name: app
        image: nginx
        command: ["/this-command-does-not-exist"]