{{- if and .Values.agent.apiKey.value (not .Values.agent.apiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: kubentic-api-key
  namespace: {{ include "kubentic-operator.namespace" . }}
  labels:
    {{- include "kubentic-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  key: {{ .Values.agent.apiKey.value | quote }}
{{- end }}
