{{- if and .Values.agent.create .Values.agent.accessToken.value (not .Values.agent.accessToken.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: kubentic-token
  namespace: {{ include "kubentic-operator.namespace" . }}
  labels:
    {{- include "kubentic-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.agent.accessToken.value | quote }}
{{- end }}
