apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubentic-operator
  namespace: {{ include "kubentic-operator.namespace" . }}
  labels:
    {{- include "kubentic-operator.labels" . | nindent 4 }}
