//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *AccessTokenRef) DeepCopyInto(out *AccessTokenRef) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

func (in *AccessTokenRef) DeepCopy() *AccessTokenRef {
	if in == nil {
		return nil
	}
	out := new(AccessTokenRef)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentOverrideSpec) DeepCopyInto(out *AgentOverrideSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *AgentOverrideSpec) DeepCopy() *AgentOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(AgentOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BackendSpec) DeepCopyInto(out *BackendSpec) {
	*out = *in
}

func (in *BackendSpec) DeepCopy() *BackendSpec {
	if in == nil {
		return nil
	}
	out := new(BackendSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *CollectionSpec) DeepCopyInto(out *CollectionSpec) {
	*out = *in
	in.Logs.DeepCopyInto(&out.Logs)
	out.Metrics = in.Metrics
}

func (in *CollectionSpec) DeepCopy() *CollectionSpec {
	if in == nil {
		return nil
	}
	out := new(CollectionSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
	if in.PullSecrets != nil {
		in, out := &in.PullSecrets, &out.PullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KubenticAgent) DeepCopyInto(out *KubenticAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *KubenticAgent) DeepCopy() *KubenticAgent {
	if in == nil {
		return nil
	}
	out := new(KubenticAgent)
	in.DeepCopyInto(out)
	return out
}

func (in *KubenticAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KubenticAgentList) DeepCopyInto(out *KubenticAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubenticAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *KubenticAgentList) DeepCopy() *KubenticAgentList {
	if in == nil {
		return nil
	}
	out := new(KubenticAgentList)
	in.DeepCopyInto(out)
	return out
}

func (in *KubenticAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KubenticAgentSpec) DeepCopyInto(out *KubenticAgentSpec) {
	*out = *in
	in.AccessToken.DeepCopyInto(&out.AccessToken)
	if in.APIKey != nil {
		in, out := &in.APIKey, &out.APIKey
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	in.Collection.DeepCopyInto(&out.Collection)
	out.Backend = in.Backend
	if in.AgentOverride != nil {
		in, out := &in.AgentOverride, &out.AgentOverride
		*out = new(AgentOverrideSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SuccessfulJobsHistoryLimit != nil {
		in, out := &in.SuccessfulJobsHistoryLimit, &out.SuccessfulJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.FailedJobsHistoryLimit != nil {
		in, out := &in.FailedJobsHistoryLimit, &out.FailedJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.ActiveDeadlineSeconds != nil {
		in, out := &in.ActiveDeadlineSeconds, &out.ActiveDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.BackoffLimit != nil {
		in, out := &in.BackoffLimit, &out.BackoffLimit
		*out = new(int32)
		**out = **in
	}
}

func (in *KubenticAgentSpec) DeepCopy() *KubenticAgentSpec {
	if in == nil {
		return nil
	}
	out := new(KubenticAgentSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KubenticAgentStatus) DeepCopyInto(out *KubenticAgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastScanTime != nil {
		in, out := &in.LastScanTime, &out.LastScanTime
		*out = (*in).DeepCopy()
	}
	if in.NextScanTime != nil {
		in, out := &in.NextScanTime, &out.NextScanTime
		*out = (*in).DeepCopy()
	}
}

func (in *KubenticAgentStatus) DeepCopy() *KubenticAgentStatus {
	if in == nil {
		return nil
	}
	out := new(KubenticAgentStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *LogCollectionSpec) DeepCopyInto(out *LogCollectionSpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *LogCollectionSpec) DeepCopy() *LogCollectionSpec {
	if in == nil {
		return nil
	}
	out := new(LogCollectionSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MetricsCollectionSpec) DeepCopyInto(out *MetricsCollectionSpec) {
	*out = *in
}

func (in *MetricsCollectionSpec) DeepCopy() *MetricsCollectionSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsCollectionSpec)
	in.DeepCopyInto(out)
	return out
}
